export * from "./auth.routes";
export * from "./company.routes";
export * from "./oligarch.routes";
export * from "./photo.routes";
export * from "./politician.routes";
export * from "./product.routes";
export * from "./project2025.routes";
export * from "./search.routes";
export * from "./user.routes";
